name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "4b5dd2bc-6c8f-4311-b48d-dc7f783adc6b"

[vars]
G_CLIENT_ID = "Iv23lizRteMASds1zTqq"
INIT_TABLE = "true"
ENABLE_CACHE = "true"
